# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b720e7f160b40b2c41d254d03c9e5db50932ad454cc0a89009718a75f37836303209a20ada938e7f7de4129b64e21746a44bbfb577533096fee7dcfbc4bb659

test:
  secret_key_base: ad7e6d52e27969c8ada1e7e26f6aa294da7593577db69bbc927f1d0e1cb6c019cb3f51956daa68f268250a0f7e30e9da40437d39e7c7a680d4f262ffaf5264fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
